### PR TITLE
bump sigstore to 2.1.5

### LINKED ISSUE #296: aiogithubapi requires sigstore < 2 which pins pydantic to 1.10.12
## The problem

When trying to install a package that requires a (more) recent pydantic release I get the following error:

```
Installing collected packages: pydantic
  Attempting uninstall: pydantic
    Found existing installation: pydantic 1.10.12
    Uninstalling pydantic-1.10.12:
      Successfully uninstalled pydantic-1.10.12
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
sigstore 1.1.2 requires pydantic~=1.10, but you have pydantic 2.7.1 which is incompatible.
Successfully installed pydantic-2.7.1
vscode ➜ /workspaces/core (dev) $ 
```

Using `pip show sigstore` it turns out this requirement comes from this library:
```
vscode ➜ /workspaces/core (dev) $ pip show sigstore
Name: sigstore
Version: 1.1.2
Summary: A tool for signing Python package distributions
Home-page: 
Author: 
Author-email: Sigstore Authors <sigstore-dev@googlegroups.com>
License: 
Location: /home/vscode/.local/lib/python3.12/site-packages
Requires: appdirs, cryptography, id, pydantic, pyjwt, pyOpenSSL, requests, securesystemslib, sigstore-protobuf-specs, tuf
Required-by: aiogithubapi
vscode ➜ /workspaces/core (dev) $
```

There are newer versions available as can be seen from `pip index versions sigstore`:
```
vscode ➜ /workspaces/core (dev) $ pip index versions sigstore
WARNING: pip index is currently an experimental command. It may be removed/changed in a future release without prior warning.
sigstore (2.1.5)
Available versions: 2.1.5, 2.1.3, 2.1.2, 2.1.0, 2.0.1, 2.0.0, 1.1.2, 1.1.1, 1.1.0, 1.0.0, 0.10.0, 0.9.0, 0.8.3, 0.7.0, 0.6.8, 0.6.7, 0.6.6, 0.6.5, 0.6.4, 0.6.3, 0.6.2, 0.6.1, 0.5.1, 0.5.0
  INSTALLED: 1.1.2
  LATEST:    2.1.5
vscode ➜ /workspaces/core (dev) $
```

I would welcome if you could update to a more recent version of sigstore so a more recent version of pydantic (and pydantic-settings) can be used by other libraries.

## Environment

- Operating system: Home Assistant development container
- Python version:
```
vscode ➜ /workspaces/core (dev) $ python -V
Python 3.12.2
vscode ➜ /workspaces/core (dev) $
```

## Problem-relevant code

Run Home Assistant development container and issue the following command in a shell
```python
pip install --upgrade pydantic
```

## Traceback/Error logs

See above.

### PR DESCRIPTION
**Pull request by jmartens**
fixes: ludeeus#296

## Proposed change
Update sigstore to latest version, 2.1.5 as of time of writing

## Type of change

- [X] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (which adds functionalit)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #296

## Checklist

- [ ] The code change is tested and works locally.
- [X] Local tests pass.
- [X] There is no commented out code in this PR.
- [ ] The code has been formatted using Black (`make lint`)
- [ ] Tests have been added to verify that the new code works.

### CODE REVIEW

**Comment by jmartens** [comment]
> Thanks 👍 But until sigstore ditches the pydantic requirement, Im not willing to bump it. 

Hmmm. That limits all current users and integrations to an outdated version of pydantic because of your preference. IMHO you are a major blocker like this since [aiogithubapi is part of the core integrations of Home Assistant](https://github.com/home-assistant/core/blob/8153ff78bfd8dd82e460d39fd4e12ef59eed8023/homeassistant/components/github/manifest.json#L7). 

I would love if you would revise your standpoint.

> I would rather ditch sigstore.

Not sure what sigstore does and why you depend on it, so hard for me to suggest a different solution for this PR. :-(

**Comment by jmartens** [comment]
A quick scout through the code base seems to indicate it is used in https://github.com/ludeeus/aiogithubapi/blob/e81c4d1e93650e3597a71956cc47cfe47637097c/aiogithubapi/helpers.py#L50 and is only referenced from https://github.com/ludeeus/aiogithubapi/blob/e81c4d1e93650e3597a71956cc47cfe47637097c/tests/test_helper.py#L45

Is this function invoked from somewhere else? Otherwise it might be even possible to remove it altogether.

**Comment by ludeeus** [comment]
It is a public function meant for consumers of this library to use.

**Comment by ludeeus** [comment]
Closing this for now as this is deprecated pending full removal.

**Pull request closed without merging**
